orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 16.13.1
      - node/test:
          version: 17.2.0
